# Generated by Django 3.2.10 on 2021-12-26 17:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="securities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security",
                "verbose_name_plural": "Securities",
            },
        ),
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "security_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="securities.security",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("government_bond", "Government bond"),
                            ("corporate_bond", "Corporate bond"),
                        ],
                        default="government_bond",
                        max_length=64,
                        verbose_name="Type",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=1024, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Bond",
                "verbose_name_plural": "Bonds",
            },
            bases=("securities.security",),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "security_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="securities.security",
                    ),
                ),
                ("symbol", models.CharField(max_length=254, verbose_name="Symbol")),
                (
                    "sector",
                    models.IntegerField(
                        choices=[
                            (10, "Energy"),
                            (15, "Materials"),
                            (20, "Industrials"),
                            (25, "Consumer Discretionary"),
                            (30, "Consumer Staples"),
                            (35, "Health Care"),
                            (40, "Financials"),
                            (45, "Information Technology"),
                            (50, "Communication Services"),
                            (55, "Utilities"),
                            (60, "Real Estate"),
                        ],
                        verbose_name="Sector",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("common_stock", "Common stock"),
                            ("preferred_stock", "Preferred stock"),
                        ],
                        default="common_stock",
                        max_length=64,
                        verbose_name="Type",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=1024, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
            bases=("securities.security",),
        ),
    ]
