# Generated by Django 4.1.7 on 2023-03-03 18:04

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=3, unique=True, verbose_name="ISO code"
                    ),
                ),
                (
                    "nominal",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Nominal"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rate",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange rate",
                "verbose_name_plural": "Exchange rates",
                "unique_together": {("currency", "date")},
            },
        ),
    ]
