version: 2
jobs:
  build:
    docker:
      - image: python:3.12
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DJANGO_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            pip install pipenv
            pipenv sync --dev
      - save_cache:
          paths:
            - ~/repo/.venv
          key: python-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Run black
          command: |
            pipenv run black . --check
      - run:
          name: Run flake8
          command: |
            pipenv run flake8 . --statistic --exclude .venv
      - run:
          name: Run isort
          command: |
            pipenv run isort **/*.py --check-only --verbose
