# Generated by Django 4.2.8 on 2025-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="close_id",
            field=models.CharField(
                blank=True,
                help_text="The unique id of the close order used to identify this action within broker's platform.",
                max_length=254,
                verbose_name="Close ID",
            ),
        ),
    ]
