# Generated by Django 4.0.4 on 2022-11-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="withheld_tax",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, null=True, verbose_name="Withheld tax"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="withheld_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Due to rounding it's better to store the rate percentage as a separate field.",
                max_digits=5,
                null=True,
                verbose_name="Withheld tax rate",
            ),
        ),
    ]
